### PR TITLE
0 based

### LINKED ISSUE #8: Function to create a 0-based adjacency list from a SparseMatrixCSC object
The `SparseMatrixCSC` methods for `nodeND` and for `vertexSep` both create the adjacency list from the sparse matrix structure.  In the case of `vertexSep` it also converts to 0-based indices for use with ParMetis.  It would be better to isolate these operations in a separate function.

### PR DESCRIPTION
**Pull request by dmbates**
Closes #8

### CODE REVIEW

**Comment by dmbates** [comment]
@poulson I was planning on merging this today.  Do you want to look at it before I do?  It does affect the `vertexSep` function.

**Comment by poulson** [comment]
It looks good to me (as long as ``runTests.jl`` passes). The only thing surprising to me is that ``mkadjCSR`` is zero-based, but ``SparseMatrixCSC`` is one-based. Maybe an extra boolean argument should be added to ``mkadjCSR`` for choosing between the two?

**Comment by dmbates** [comment]
Perhaps it would be better if I changed the name of the `mkadjCSR` function.  It is not intended to produce a valid Julia sparse matrix.  It simply creates the 0-based column pointers and row/column indices from the CSC/CSR representation of the adjacency matrix.  I could call it something like `metisform` to indicate that it produces the form using by Metis.

**Comment by poulson** [comment]
I agree that such a name would be more intuitive.

**Pull request merged**
