### PR TITLE
tap from homebrew/science.

### PR DESCRIPTION
**Pull request by dpo**
The METIS bottle in Homebrew/science is `cellar :any`.

### CODE REVIEW

**Comment by tkelman** [comment]
I think this would be better and should still work if it changed the provides to "homebrew/science/metis" since bindeps is supposed to be declarative

**Comment by dpo** [comment]
Let's find out.

**Comment by tkelman** [comment]
lgtm, though travis is using the old-style ppa instead of the new-style `language: julia` which could test the package on osx

**Comment by dpo** [comment]
Linux/OSX: https://travis-ci.org/dpo/dpo/Metis.jl/builds/85907922
There's an issue on Linux with `git fetch --unshallow`: https://travis-ci.org/dpo/dpo/Metis.jl/jobs/85907923#L100

Windows: https://ci.appveyor.com/project/dpo/metis-jl/build/1.0.2
WinRPM issues on all 32-bit platforms: https://ci.appveyor.com/project/dpo/metis-jl/build/1.0.2/job/t3apqea4olcmw4qd#L63

**Comment by tkelman** [comment]
Thanks for turning those on. The unshallow thing has been reported on travis' issue tracker, I unfortunately don't know what's going on. Maybe switching the `sudo` or trying the new `dist: trusty` could help?

The 32 bit problem is breakage in Zlib.jl, I have a PR open.

**Comment by dpo** [comment]
I've been overwhelmed by the popularity of this PR. But now that [`metis` moved to `homebrew/core`](https://github.com/Homebrew/homebrew-core/pull/15838), it need no longer exist.

**Pull request closed without merging**
