### PR TITLE
Exposing full functionality of METIS_PartGraphKway function

### PR DESCRIPTION
**Pull request by timmoon10**
The partitioner can now accommodate edge weights, vertex weights, and other features available in METIS_PartGraphKway function. Similar changes can be performed in other functions to expose full METIS functionality.

### CODE REVIEW

**Comment by dmbates** [comment]
Can you add some tests of these new capabilities?

**Comment by timmoon10** [comment]
I've added a few tests with path graphs and wheel graphs to verify that the partitioner works with vertex weights and edge weights.

**Comment by dmbates** [comment]
Does anyone understand why the summary of the PR states that 16,146 lines have been changed with 434 additions and 15,712 deletions?

**Comment by timmoon10** [comment]
I think it's because I removed graph/4elt.graph, which was unused. I can put it back to make the change a little smaller.

**Comment by dmbates** [comment]
@timmoon10 It is fine to have removed that file as it was not being used.  I was just surprised to see the summary with such a large number of line removals and I couldn't see where this came from.

This looks good to me.  Unless others have comments I will merge it later this evening.

**Pull request closed without merging**
