### PR TITLE
metisform for LightGraphs

### PR DESCRIPTION
**Pull request by sbromberger**
includes tests.

Also: sorry about all the whitespace changes - my editor removes EOL whitespace for Julia by default.

### CODE REVIEW

**Comment by sbromberger** [comment]
Hm. First test failed due to is_directed. Checking again.

**Comment by dmbates** [comment]
It is okay to go through the adjacency matrix.  I was contemplating directly building the metisform and skipping the adjacency matrix. I'll merge this then, unless you feel it is ill-advised, rewrite the metisform method.

By the way, thanks for catching the trailing whitespace, which may have been done automatically.

**Comment by sbromberger** [comment]
Given your update to https://gist.github.com/sbromberger/46125252ac26714dfc7e, it seems more straightforward to just use the adjacency matrix :) It's so fast now that I'm not sure I could optimize it any better.

**Comment by dmbates** [comment]
As it stands, adjacency_matrix copies the information about the edges (both directions) into a `SparseMatrixCSC` structure, with a redundant `nzval` field, then `metisform` copies one half of that structure and drops the `nzval` information. I was planning on rewriting the metisform method to avoid the intermediate copy.

**Comment by sbromberger** [comment]
Ah, I see. It does look like I took the lazy way out :) I can give it a try this weekend.

I've updated my LightGraphs.jl documentation to include Metis support.

**Comment by dmbates** [comment]
I just pushed a commit with a version of `metisform` that generates the `xadj` and `adjncy` vectors directly from a `LightGraphs.Graph` object.

**Comment by sbromberger** [comment]
Nice! The only worry I have is that attributes of Graph shouldn't necessarily be exposed to other packages (e.g., `g.finclist`) since it will be harder to change the internal structures later if we need to. But I guess it's ok here.

**Comment by dmbates** [comment]
Could you write a simple extractor function in LightGraphs that returns the destination vertices of edges from vertex i?  That's all that is needed here.

**Comment by sbromberger** [comment]
Yes, but: accessing edges via finclist (vector) is much faster than via edges(g), which is a set. You've got it optimized for speed already. I'm ok with this sort of access, especially since it's not exposed anywhere else.

**Comment by dmbates** [comment]
I wasn't thinking of getting all edges, just the edges that originate at vertex i.  It would be something like
```julia
outgoing_edges(g::AbstractGraph,i::Integer) = [dst(e) for e in g.finclist[i]]
```

Also, have you considered templating the Graph and DiGraph types to allow for different integer types to represent an edge?  Usually the number of vertices will be less than `typemax(Int32)` and using `Int32` instead of `Int` saves you half the storage on a 64-bit system.

**Comment by sbromberger** [comment]
Ah, sorry - I misunderstood what you needed. Use out_neighbors(g, v) to get the outbound neighbors of a given vertex v. (This uses finclist).

As far as type parameterization, I could certainly look into doing that.

**Pull request merged**
